package ServerClient;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author viniciuscustodio
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Server
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jlServerPort = new javax.swing.JLabel();
        jtServerPort = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbZero = new javax.swing.JButton();
        jbOne = new javax.swing.JButton();
        jbTwo = new javax.swing.JButton();
        jbThree = new javax.swing.JButton();
        jbFour = new javax.swing.JButton();
        jbFive = new javax.swing.JButton();
        jbSix = new javax.swing.JButton();
        jbSeven = new javax.swing.JButton();
        jbEight = new javax.swing.JButton();
        jbNine = new javax.swing.JButton();
        jbSum = new javax.swing.JButton();
        jbMultiply = new javax.swing.JButton();
        jbSubtract = new javax.swing.JButton();
        jbDivide = new javax.swing.JButton();
        jbSqrt = new javax.swing.JButton();
        jbInverse = new javax.swing.JButton();
        jbEqual = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jtExpression = new javax.swing.JTextField();
        jtServerIP = new javax.swing.JTextField();
        jlServerIP = new javax.swing.JLabel();
        jlClientPort = new javax.swing.JLabel();
        jtClientPort = new javax.swing.JTextField();

        jButton17.setText("1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlServerPort.setText("ServerPort:");

        jtServerPort.setText("10000");
        jtServerPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtServerPortActionPerformed(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jbZero.setText("0");
        jbZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbZeroActionPerformed(evt);
            }
        });
        jbZero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbZeroKeyPressed(evt);
            }
        });

        jbOne.setText("1");
        jbOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOneActionPerformed(evt);
            }
        });

        jbTwo.setText("2");
        jbTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTwoActionPerformed(evt);
            }
        });

        jbThree.setText("3");
        jbThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThreeActionPerformed(evt);
            }
        });

        jbFour.setText("4");
        jbFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFourActionPerformed(evt);
            }
        });

        jbFive.setText("5");
        jbFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFiveActionPerformed(evt);
            }
        });

        jbSix.setText("6");
        jbSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSixActionPerformed(evt);
            }
        });

        jbSeven.setText("7");
        jbSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSevenActionPerformed(evt);
            }
        });

        jbEight.setText("8");
        jbEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEightActionPerformed(evt);
            }
        });

        jbNine.setText("9");
        jbNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNineActionPerformed(evt);
            }
        });

        jbSum.setText("+");
        jbSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSumActionPerformed(evt);
            }
        });

        jbMultiply.setText("*");
        jbMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultiplyActionPerformed(evt);
            }
        });

        jbSubtract.setText("-");
        jbSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubtractActionPerformed(evt);
            }
        });

        jbDivide.setText("/");
        jbDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivideActionPerformed(evt);
            }
        });

        jbSqrt.setText("√");
        jbSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSqrtActionPerformed(evt);
            }
        });

        jbInverse.setText("1/x");
        jbInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInverseActionPerformed(evt);
            }
        });

        jbEqual.setText("=");
        jbEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEqualActionPerformed(evt);
            }
        });

        jbClear.setText("Clear");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNine, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSum, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFour, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFive, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSix, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOne, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbThree, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbZero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtExpression.setEnabled(false);

        jtServerIP.setText("127.0.0.1");

        jlServerIP.setText("ServerIP:");

        jlClientPort.setText("ClientPort:");

        jtClientPort.setText("10001");
        jtClientPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtClientPortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlClientPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlServerPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlServerIP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlServerPort)
                    .addComponent(jtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlServerIP)
                    .addComponent(jtServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlClientPort)
                    .addComponent(jtClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbZeroActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "0");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbZeroActionPerformed

    private void jbOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOneActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "1");
    }//GEN-LAST:event_jbOneActionPerformed

    private void jbTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTwoActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "2");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbTwoActionPerformed

    private void jbThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThreeActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "3");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbThreeActionPerformed

    private void jbFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFourActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "4");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFourActionPerformed

    private void jbFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFiveActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "5");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFiveActionPerformed

    private void jbSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSixActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "6");

    }//GEN-LAST:event_jbSixActionPerformed

    private void jbSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSevenActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "7");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSevenActionPerformed

    private void jbEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEightActionPerformed
        if (hasEqual()) {
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "8");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEightActionPerformed

    private void jbNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNineActionPerformed
        if(hasEqual()){
            jtExpression.setText("");
        }
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "9");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNineActionPerformed

    private void jbSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSumActionPerformed
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "+");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSumActionPerformed

    private void jbSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubtractActionPerformed
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "-");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSubtractActionPerformed

    private void jbMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplyActionPerformed
        String expression = jtExpression.getText();
        jtExpression.setText(expression + "*");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMultiplyActionPerformed

    private void jbDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivideActionPerformed

        String expression = jtExpression.getText();
        jtExpression.setText(expression + "/");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDivideActionPerformed

    private void jbInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInverseActionPerformed
        jtExpression.setText("1/" + jtExpression.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_jbInverseActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        jtExpression.setText("");
    }//GEN-LAST:event_jbClearActionPerformed

    private void jtServerPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtServerPortActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jtServerPortActionPerformed

    private void jtClientPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtClientPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtClientPortActionPerformed

    private void jbEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEqualActionPerformed
        try {
            sentToServer();
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbEqualActionPerformed

    private void jbZeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbZeroKeyPressed
        jbZeroActionPerformed(new ActionEvent(jbZero, WIDTH, null));
        // TODO add your handling code here:
    }//GEN-LAST:event_jbZeroKeyPressed

    private void jbSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSqrtActionPerformed
        jtExpression.setText("√" + jtExpression.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSqrtActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed
    private boolean hasEqual() {
        return jtExpression.getText().contains("=");
    }

    private void sentToServer() throws IOException {
        UDPCliente client = new UDPCliente();
        String result = client.calculator(jtExpression.getText(), Integer.parseInt(jtClientPort.getText()), Integer.parseInt(jtServerPort.getText()), jtServerIP.getText());
        jtExpression.setText(jtExpression.getText() + " = " + result);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbDivide;
    private javax.swing.JButton jbEight;
    private javax.swing.JButton jbEqual;
    private javax.swing.JButton jbFive;
    private javax.swing.JButton jbFour;
    private javax.swing.JButton jbInverse;
    private javax.swing.JButton jbMultiply;
    private javax.swing.JButton jbNine;
    private javax.swing.JButton jbOne;
    private javax.swing.JButton jbSeven;
    private javax.swing.JButton jbSix;
    private javax.swing.JButton jbSqrt;
    private javax.swing.JButton jbSubtract;
    private javax.swing.JButton jbSum;
    private javax.swing.JButton jbThree;
    private javax.swing.JButton jbTwo;
    private javax.swing.JButton jbZero;
    private javax.swing.JLabel jlClientPort;
    private javax.swing.JLabel jlServerIP;
    private javax.swing.JLabel jlServerPort;
    private javax.swing.JTextField jtClientPort;
    private javax.swing.JTextField jtExpression;
    private javax.swing.JTextField jtServerIP;
    private javax.swing.JTextField jtServerPort;
    // End of variables declaration//GEN-END:variables
}
